import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { NavigationRefsProvider } from "@/context/NavigationRefsContext";
import { ContentDataProvider } from "@/context/ContentDataContext";
import { getData } from "@/lib/db/getData";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{children: React.ReactNode;}>) {
  const pageContent = getData()
  return (
  
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-primary-light text-primary-dark dark:bg-primary-dark dark:text-primary-light`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <ContentDataProvider pageContent={pageContent}>
            <NavigationRefsProvider>
              {children}
            </NavigationRefsProvider>
          </ContentDataProvider>
            
        </ThemeProvider>
      </body>
    </html>
    
    
  );
}
